---
title: "8 Schools"
author: "Stephen, Kostis, Jie"
date: "March 1, 2016"
output: 
  pdf_document: 
    fig_height: 4
    fig_width: 5
    keep_tex: yes
---



```{r, include=FALSE}
library(rstan)
library(dplyr)
rstan_options(auto_write=TRUE)
set.seed(1)
```

Simple fit and objects from said fit:

```{r}
birth_death_ssa <- function(alpha,
                            mu,
                            x0,
                            Time){
    
    x <- x0
    t <- 0
    i=2
    while(t[length(t)]<Time){
        a_sum <- alpha+mu*x[i-1]
        xi_1 <- runif(1)
        xi_2 <- runif(1)
        rxn <- ifelse(xi_1*a_sum>alpha, -1, 1)
        tau <- log(1/xi_2)/a_sum
        x[i] <- x[i-1]+rxn
        t[i] <- t[i-1]+tau
        i <- i+1
    }
    return(list(x=x, t=t))
}

ssa_1 <- birth_death_ssa(alpha=1, mu=.1, x0=20, Time=50)
ssa_1$N <- length(ssa_1$x)

tic <- Sys.time()
initial_fit <- stan(file = '../stan_model_files/poisson-model.stan', data = ssa_1, 
                    iter = 10000, chains = 4)
toc <- Sys.time()
toc-tic

print(initial_fit)
plot(initial_fit)
pairs(initial_fit)

la <- extract(initial_fit, permuted = TRUE) # return a list of arrays 
mu <- la$mu 

### return an array of three dimensions: iterations, chains, parameters 
a <- extract(initial_fit, permuted = FALSE) 

### use S3 functions as.array (or as.matrix) on stanfit objects
a2 <- as.array(initial_fit)
m <- as.matrix(initial_fit) %>%
    as.data.frame() %>%
    mutate(chain=rep(seq(1,4),each=500),
           iteration=rep(seq(1,500),4))
qplot(data=m, x=iteration, y=mu, color=as.factor(chain), geom="line", alpha=0.6) +
    theme_bw()
```
